server:
  port : 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/infinityfarm
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true